import Head from "next/head";
import { FoundNewsLists } from "../../components/features/foundNewsLists";
import { TopLatestNews } from "../../components/features/topLatestNews";
import { Divider } from "../../components/shared/divider";
import { Layout } from "../../components/templates/layout";
import { contentfulDataFetching } from "../../helpers/contentfulDataFetching";
import { ContentFulApiResponse } from "../../interfaces/contentFulApiResponse";

const Home = (props: ContentFulApiResponse) => {
  const { logoDetails, menuLabel, searchLabel, pageTitle } = props;
  return (
    <div>
      <Head>
        <title>{pageTitle}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout logoDetails={logoDetails} menuLabel={menuLabel}>
        <main className="py-8 ">
          <TopLatestNews />
          <Divider className="my-6" />
          <FoundNewsLists searchLabel={searchLabel} />
        </main>
      </Layout>
    </div>
  );
};

export async function getServerSideProps() {
  try {
    const contentFulResponse: ContentFulApiResponse =
      await contentfulDataFetching();
    return {
      props: {
        ...contentFulResponse,
      },
    };
  } catch (err) {
    return { notFound: true };
  }
}

export default Home;
