import type { NextPage } from "next";
import Head from "next/head";
import { NewsCard } from "../components/features/news";
import { Container } from "../components/shared/container";
import { Footer } from "../components/templates/footer";
import { Header } from "../components/templates/header";
import { NewsItem } from "../interfaces/newsItem";
import { Divider } from "../components/shared/divider/divider";
import SearchIcon from "@mui/icons-material/Search";
import IconButton from "@mui/material/IconButton";
import TextField from "@mui/material/TextField";
import InputAdornment from "@mui/material/InputAdornment";
import { getNewsItems } from "../lib/contentfulService";
import { ContentFulNewsConfig } from "../interfaces/contentFulNewsConfig";
import { LogoDetails } from "../interfaces/logoDetails";

interface ContentFulApiResponse {
  logoDetails: LogoDetails;
  menuLabel: string;
  searchLabel: String;
  pageTitle: String;
}
const dataLists: NewsItem[] = [
  {
    title: "Awe",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    name: "What is Your Non-adhd partner thinking ?",
    organizationFieldName: "Psychology Today",
    publicationDate: new Date(),
  },
  {
    title: "Awe",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    name: "What is Your Non-adhd partner thinking ?",
    organizationFieldName: "Psychology Today",
    publicationDate: new Date(),
  },
  {
    title: "Awe",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    name: "What is Your Non-adhd partner thinking ?",
    organizationFieldName: "Psychology Today",
    publicationDate: new Date(),
  },
];

const Home = (props: ContentFulApiResponse) => {
  const { logoDetails, menuLabel, searchLabel, pageTitle } = props;
  return (
    <div>
      <Head>
        <title>{pageTitle}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header logoDetails={logoDetails} menuLabel={menuLabel} />
        <main className="py-8 ">
          <section className="top-latest-news">
            <Container>
              <div className="flex items-center justify-center pt-12 pb-24">
                <h2 className="text-5xl font-bold text-primary-500">
                  CredibleMind in the news
                </h2>
              </div>

              <div className="wrapper grid grid-cols-3 gap-5">
                <NewsCard
                  news={{
                    title: "Awe",
                    description:
                      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                    name: "What is Your Non-adhd partner thinking ?",
                    organizationFieldName: "Psychology Today",
                    publicationDate: new Date(),
                  }}
                  isCardLayout={true}
                ></NewsCard>
                <NewsCard
                  news={{
                    title: "Awe",
                    description:
                      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                    name: "What is Your Non-adhd partner thinking ?",
                    organizationFieldName: "Psychology Today",
                    publicationDate: new Date(),
                  }}
                  isCardLayout={true}
                ></NewsCard>
                <NewsCard
                  news={{
                    title: "Awe",
                    description:
                      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                    name: "What is Your Non-adhd partner thinking ?",
                    organizationFieldName: "Psychology Today",
                    publicationDate: new Date(),
                  }}
                  isCardLayout={true}
                ></NewsCard>
              </div>
            </Container>
          </section>
          <Divider className="my-6" />
          <section className="found-news-list">
            <Container className="grid grid-cols-4 relative gap-8">
              <div className="search-and-filter sticky top-0">
                <div className="wrapper border p-4">
                  <h4 className="text-xl mt-2 mb-8">{searchLabel}</h4>
                  <TextField
                    label="Search"
                    className="items"
                    InputProps={{
                      endAdornment: (
                        <InputAdornment position="end">
                          <IconButton className="rounded-none bg-secondary  text-white">
                            <SearchIcon />
                          </IconButton>
                        </InputAdornment>
                      ),
                    }}
                  />
                </div>
              </div>
              <div className="display-list col-span-3">
                <h3 className="text-2xl font-bold text-primary-400">
                  {dataLists.length} Resources Found
                </h3>
                <Divider className="mt-6 mb-9" />
                <div className="grid grid-cols-1 items-center gap-8">
                  {dataLists.map((dataItem, index) => {
                    return (
                      <>
                        <NewsCard
                          news={dataItem}
                          key={`${index}:${dataItem.title}`}
                        />
                        <Divider />
                      </>
                    );
                  })}
                </div>
              </div>
            </Container>
          </section>
        </main>
        <Footer />
      </main>
    </div>
  );
};

export async function getServerSideProps() {
  const fields: ContentFulNewsConfig | undefined = await getNewsItems();

  let logoUrl: String,
    logoWidth: number,
    logoHeight: number,
    logoTitle: String,
    menuLabel: String,
    searchLabel: String,
    pageTitle: String;


    logoUrl = "/vercel.svg";
    logoWidth = 150;
    logoHeight = 50;
    logoTitle = "";
    menuLabel = "News";
    searchLabel = "Filter & Refine";
    pageTitle = "CredibleMind Cm test task";

  if (fields) {
    // logo details
    const {
      logo: {
        fields: {
          title: responseLogoTitle,
          file: {
            url: responseLogoUrl,
            details: {
              image: { width: responseLogoWidth, height: responseLogoHeight },
            },
          },
        },
      },
      menuLabel: responseMenuLabel,
      searchLabel: responseSearchLabel,
      title: responsePageTitle,
    } = fields;
    


    logoUrl = responseLogoUrl;
    logoWidth = responseLogoWidth;
    logoHeight = responseLogoHeight;
    logoTitle = responseLogoTitle;
    menuLabel = responseMenuLabel;
    searchLabel = responseSearchLabel;
    pageTitle = responsePageTitle;
  }

  return {
    props:{
      logoDetails: { logoUrl, logoHeight, logoWidth, logoTitle },
    menuLabel,
    searchLabel,
    pageTitle,
    }
  };
};

export default Home;
